name: Build Windows EXE

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.12

    - name: Install dependencies
      run: pip uninstall -y bcrypt py-bcrypt bcryptor || true && python -m pip install --upgrade pip && pip install --force-reinstall pyinstaller rich questionary mysql-connector-python prompt_toolkit keyring passlib[bcrypt] "bcrypt>=4.0.1" cffi

    - name: Build executable
      run: pyinstaller --onefile --icon="Naval Fleet Management System/icon/icon.ico" --exclude-module=keyring.alt --hidden-import=passlib.handlers.bcrypt --hidden-import=bcrypt --hidden-import=cffi "Naval Fleet Management System/main.py"

    - name: Upload build artifact
      uses: actions/upload-artifact@v4
      with:
        name: windows-executable
        path: dist/
